categories = [
  "personal_information",
  "emotional_venting",
  "problem_solving_advice_seeking",
  "informational_discourse",
  "philosophical_ideas_opinions",
  "relationship_discussions",
  "professional_career_work",
  "hobbies_interests",
  "travel_and_food",
  "conflict_resolution",
  "health_and_well_being",
  "news_current_events",
  "social_support_validation",
]